export default [
    ["avoid", "/əˈvɔɪd/", "Try to avoid the motorway because there is a huge traffic jam.", "избегать, остерегаться, сторониться, уклоняться"],
    ["bus stop", "/ˈbʌs stɒp/", "You can buy a ticket at the bus stop.", "авто́бусная остано́вка"],
    ["car crash", "/kɑː(r) kræʃ/", "I broke my leg in a car crash last month.", "автомобильная катастрофа"],
    ["carriage", "/ˈkærɪdʒ/", "My seat is in carriage F.", "коляска; экипаж; карета; повозка;железнодорожный вагон "],
    ["child seat", "/tʃaɪld siːt/", "You should buy a child seat for your car. ", "детское кресло"],
    ["coach", "/kəʊtʃ/", "We went on a coach to France.", "одноэтажный автобус;"],
    ["cross", "/krɒs/", "What’s the quickest way to cross a busy city?", "пересекать, переходить; скрещивать"],
    ["cycle lane", "/ˈsaɪkl leɪn/", "It’s safer to use a cycle lane when you’re on your bike.", "велосипедная полоса"],
    ["end up", "/end ʌp/", "People end up multitasking, which can make them even more stressed.", "оказаться"],
    ["get stuck", "/ɡet stʌk/", "I always get stuck in traffic on my way to work.", "застрять"],
    ["go over", "/ɡəʊ ˈəʊvə(r)/", "Don’t go over the speed limit.", "переходить, пересекать (фраз. гл.)"],
    ["lorry", "/ˈlɒri/", "My brother drives a lorry.", "грузовой автомобиль"],
    ["motorway", "/ˈməʊtəweɪ/", "The speed limit is 70 miles per hour on the motorway in the UK.", "автострада, автомагистраль"],
    ["parking fine", "/ˈpɑːkɪŋ faɪn/", "I left my car on double yellow lines and I got a parking fine.", "штраф за паркову"],
    ["pedestrian crossing", "/pəˌdestriən ˈkrɒsɪŋ/", "Children should always use a pedestrian crossing.", "пешеходный переход"],
    ["petrol station", "/ˈpetrəl steɪʃn/", "I stopped at a petrol station to fill up the car.", "автозаправочная станция"],
    ["platform", "/ˈplætfɔːm/", "The train leaves from this platform.", "перрон, платформаплатформа; помосттрибуна; сцена, эстрада"],
    ["roadworks", "/ˈrəʊdwɜːks/", "Roadworks are starting on this road next week so traffic will be bad.", "ремонтные работы на дороге"],
    ["run out", "/rʌn aʊt/", "What will we do if we run out of petrol?", "кончаться, иссякать;выдыхаться; задыхаться;выгнать"],
    ["rush hour", "/ˈrʌʃ aʊə(r)/", "The traffic is always bad in rush hour.", "час пик"],
    ["scooter", "/ˈskuːtə(r)/", "My daughter uses her scooter to get to work.", "детский самокат;мотороллер "],
    ["seat belt", "/ˈsiːt belt/", "You must wear a seat belt in cars in this country.", "ремень безопасности"],
    ["set off", "/set ɒf/", "We set off early to avoid the traffic.", "отправляться (в путь); намереваться (сделать что-л.)   phr v"],
    ["speed camera", "/spiːd ˈkæmərə/", "There’s a speed camera over there so don’t drive too fast.", "камера фиксирующая скорость"],
    ["speed limit", "/ˈspiːd lɪmɪt/", "What’s the speed limit on this road?", "максимальная скорость, которую может развить транспортное средств"],
    ["taxi rank", "/ˈtæksi rænk/", "There’s a taxi rank outside the station.", "taxi rank"],
    ["traffic jam", "/ˈtræfɪk dʒæm/", "Sorry I’m late – there was a terrible traffic jam.", "пробка\", затор (в уличном движении)"],
    ["traffic lights", "/ˈtræfɪk laɪts/", "Turn right after the traffic lights.", "светофор"],
    ["tram", "/træm/", "I go to work by tram.", "трамвай"],
    ["Underground", "/ˈʌndəɡraʊnd/", "I use the London Underground every day.", "метрополитен"],
    ["van", "/væn/", "My uncle is a builder and he has his own van.", "фургон;багажный вагон, товарный вагон"],
    ["watch / look out!", "/wɒtʃ aʊt / lʊk aʊt/", "Look out!! You’re going to crash!", "быть настороже, берегись!, осторожно!"],
    ["zebra crossing", "/ˌzebrə ˈkrɒsɪŋ/", "It’s safest to cross the road at the zebra crossing.", "zebra crossing"],
    ["afraid of", "/əˈfreɪd ɒv/", "I’m afraid of spiders.", "afraid of"],
    ["angry with", "/ˈæŋɡri wɪð/", "Are you still angry with me?", "Злиться на кого то"],
    ["apologize to", "/əˈpɒlədʒaɪz tə/", "You should apologize to your sister for breaking her hairdryer.", "извиняться перед кем либо"],
    ["argue with", "/ˈɑːɡjuː wɪð/", "I always argue with my parents about when I have to be home.", "спорить с"],
    ["arrive at", "/əˈraɪv æt/", "We arrive at Heathrow at 10.30 a.m.", "достигать, прибывать КО ВРЕМЕНИ"],
    ["arrive in", "/əˈraɪv ɪn/", "What time do you arrive in London?", "достигать, прибывать НА МЕСТО"],
    ["ask for", "/ɑːsk fɔː/", "I want to ask for some help with my homework.", "просить что-либо/о чем-либо"],
    ["belong to", "/bɪˈlɒŋ tə/", "Who does this jacket belong to?", "пренадлежать кому-то, пренадлежать кому-то, принадлежать чему-то"],
    ["choose between", "/tʃuːz bɪˈtwiːn/", "You have to choose between these two dresses.", "выбрать между чем либо"],
    ["close to", "/kləʊs tə/", "I’m very close to my mum and we speak on the phone every day.", "близко(близким) к кому-то , чему-то, рядом с/близко к"],
    ["depend on", "/dɪˈpend ɒn/", "I might go to university – it will depend on my exam results.", "зависеть от, Зависеть от (кого-то, чего-то)"],
    ["different from", "/ˈdɪfrənt frɒm/", "This house is very different from your last one.", "в отличии от/ отличается от, в отличие"],
    ["dream about", "/driːm əˈbaʊt/", "Do you often dream about work?", "мечтать об/о, грезить о, мечтать о"],
    ["excited about", "/ɪkˈsaɪtɪd əˈbaʊt/", "Are you excited about your holiday?", "волноваться о чем либо"],
    ["famous for", "/ˈfeɪməs fɔː/", "What’s your hometown famous for?", "знаменит благодаря, быть известным за что-то"],
    ["fed up with", "/fed ʌp wɪð/", "I’m fed up with tidying away your clothes all the time.", "быть сытым по горло, надоесть, сытый по горло"],
    ["fond of", "/fɒnd ɒv/", "I’m fond of my niece – she’s so sweet.", "испытывающий нежные чувства к кому-либо; любящий что-либо делать"],
    ["frightened of", "/ˈfraɪtnd ɒv/", "Are you frightened of heights?", "Напуган чем-то"],
    ["good at", "/ɡʊd æt/", "I’m good at maths but I’m useless at history.", "хорошо уметь что-либо."],
    ["good for", "/ɡʊd fɔː/", "Doing some exercise every day is good for you.", "хорошо кому то/чему то"],
    ["interested in", "/ˈɪntrəstɪd ɪn/", "I’m interested in history.", "быть чем-то заинтересованным, заинтересован в"],
    ["keen on", "/kiːn ɒn/", "I’m keen on football so I watch it most weekends.", "увлекаться, интересоваться чем то, быть вовлеченным во что-либо"],
    ["kind to", "/kaɪnd tə/", "Please be kind to your little brother.", "добр (/добрый) к"],
    ["laugh at", "/lɑːf æt/", "Don’t laugh at me -when I’m talking.", "смеяться над"],
    ["look forward to", "/lʊk ˈfɔːwəd tə/", "I look forward to seeing you next week.", "ожидать с нетерпением; предвкушать"],
    ["married to", "/ˈmærid tə/", "How long have you been married to your wife?", "замужем за кем то"],
    ["pay for", "/peɪ fɔː/", "How much did you pay for that car?", "расплачиваться (за ошибку и т.п.)"],
    ["pleased about", "/pliːzd əˈbaʊt/", "Are you pleased about the new tax system?", "довольный чем либо"],
    ["proud of", "/praʊd ɒv/", "I’m really proud of my nephew as he’s now a doctor.", "гордый за что-либо, гордиться"],
    ["remind me to", "/rɪˈmaɪnd mi tə/", "Can you remind me to call your grandma tomorrow?", "напоминать о чем то"],
    ["rude to", "/ruːd tə/", "Don’t be rude to your father!", "грубый, оскорбительный, невежливый с кем либо"],
    ["scared of", "/skeəd ɒv/", "I’m scared of the dark.", " быть напуганным, бояться чего-то"],
    ["spend money on", "/spend ˈmʌni ɒn/", "I like to spend money on good quality food.", "тратить, расходовать на что либо"],
    ["tired of", "/ˈtaɪəd ɒv/", "I’m tired of working – I need to have a rest.", "устать от чего либо"],
    ["worried about", "/ˈwʌrid əˈbaʊt/", "I’m worried about Jody – she seems really depressed.", "обеспокоенный чем либо"],
    ["according to", "/əˈkɔːdɪŋ tə/", "According to the article, women are better at multitasking.", ""],
    ["adventure n", "/ədˈventʃə(r)/", "I want an adventure so let’s go travelling together.", ""],
    ["ahead of prep", "/əˈhed ɒv/", "The car was ahead of the bike.", ""],
    ["almost adv", "/ˈɔːlməʊst/", "I can talk to my wife about almost anything.", ""],
    ["choke v", "/tʃəʊk/", "Try not to choke on that apple.", ""],
    ["claim v", "/kleɪm/", "They claim that women use more words than men.", ""],
    ["confusing adj", "/kənˈfjuːzɪŋ/", "The map was confusing and we got lost.", ""],
    ["credible adj", "/ˈkredəbl/", "I don’t think this research is credible so I don’t trust the findings.", ""],
    ["fit v", "/fɪt/", "They want to fit me with a hearing aid.", ""],
    ["generally adv", "/ˈdʒenrəli/", "Generally speaking, are women more talkative than men?", ""],
    ["gossip n", "/ˈɡɒsɪp/", "Have you got any gossip to share?", ""],
    ["gossip v", "/ˈɡɒsɪp/", "She likes to gossip with her friends over coffee.", ""],
    ["hardly adv", "/ˈhɑːdli/", "We hardly ever go to the cinema any more.", ""],
    ["in fact", "/ɪn fækt/", "We don’t eat out much, in fact, we don’t even have takeaways.", ""],
    ["manual n", "/ˈmænjuəl/", "I need a training manual on how to bring up children.", ""],
    ["multitask v", "/ˌmʌltiˈtɑːsk/", "Do you think women can multitask better than men?", ""],
    ["permit n", "/ˈpɜːmɪt/", "Do you have a permit to park here?", ""],
    ["race n", "/reɪs/", "I won the race.", ""],
    ["range v", "/reɪndʒ/", "There is a wide range of products to choose from.", ""],
    ["reach v", "/riːtʃ/", "When do you think you will reach the station?", ""],
    ["recorder n", "/rɪˈkɔːdə(r)/", "They attached a recorder to them to monitor their conversations.", ""],
    ["reduce v", "/rɪˈdjuːs/", "Laughing can reduce stress.", ""],
    ["route n", "/ruːt/", "Which is the best route to the station?", ""],
    ["rush v", "/rʌʃ/", "I was late so I had to rush to school.", ""],
    ["sceptical adj", "/ˈskeptɪkl/", "They are sceptical of the belief that women use more words than men.", ""],
    ["slightly adv", "/ˈslaɪtli/", "Men only use slightly fewer words than women.", ""],
    ["stereotype n", "/ˈsteriətaɪp/", "The stereotype of British people is that they always talk about the weather.", ""],
    ["stereotype v", "/ˈsteriətaɪp/", "They stereotype women as being better at looking after children.", ""],
    ["stick v", "/stɪk/", "Men usually stick to one subject for longer when they chat.", ""],
    ["swap v", "/swɒp/", "We like to get together and swap opinions.", ""],
    ["talk about phr v", "/tɔːk əˈbaʊt/", "I like to talk about politics with my friends.", ""],
    ["tend v", "/tend/", "Women tend to gossip more than men.", ""],
    ["turn around phr v", "/ˈtɜːn əraʊnd/", "You should turn around because you’re going the wrong way.", ""],
    ["turn red", "/tɜːn red/", "When the lights turn red you have to stop.", ""],
    ["whereas conj", "/ˌweərˈæz/", "Women talk about lots of subjects whereas men usually stick to one subject for longer.", ""],
    ["worse adj", "/wɜːs/", "You should leave now because the traffic is getting worse.", ""],
    ["check-in desk n", "/tʃek ɪn desk/", "Go straight to the check-in desk when you get to the airport.", ""],
    ["commando n", "/kəˈmɑːndəʊ/", "He was a commando in the British army.", ""],
    ["do your hair", "/də jɔː(r) heə(r)/", "How long does it take to do your hair?", ""],
    ["driving simulator n", "/ˈdraɪvɪŋ ˈsɪmjuleɪtə(r)/", "A British car magazine tested drivers in a driving simulator.", ""],
    ["illegal adj", "/ɪˈliːɡl/", "Have you ever done something illegal?", ""],
    ["mile n", "/maɪl/", "How long does it take you to walk one mile?", ""],
    ["military precision n", "/ˈmɪlətri prɪˈsɪʒn/", "Getting him ready for school requires military precision.", ""],
    ["mobile n", "/ˈməʊbaɪl/", "I left my mobile on the bus!", ""],
    ["motorboat n", "/ˈməʊtəbəʊt/", "My brother bought a motorboat last weekend.", ""],
    ["nickname n", "/ˈnɪkneɪm/", "Did you have a nickname when you were at school?", ""],
    ["overground train n", "/ˈəʊvəɡraʊnd treɪn/", "You should take the overground train from Waterloo.", ""],
    ["penalty n", "/ˈpenəlti/", "Their best player missed the penalty.", ""],
    ["public transport n", "/ˈpʌblɪk ˈtrænspɔːt/", "I never use public transport because I love driving.", ""],
    ["publish v", "/ˈpʌblɪʃ/", "Will they publish your article in the magazine next month?", ""],
    ["put make-up on", "/pʊt meɪk ʌp ɒn/", "She needs 20 minutes to put make-up on in the mornings.", ""],
    ["ring road n", "/ˈrɪŋ rəʊd/", "You have to drive round the ring road to get to that part of town.", ""],
    ["rucksack n", "/ˈrʌksæk/", "I put my lunch box into my rucksack.", ""],
    ["satnav n", "/ˈsætnæv/", "I use my satnav when I go on long journeys.", ""],
    ["series n", "/ˈsɪəriːz/", "Top Gear is a very popular TV series.", ""],
    ["silence is golden", "/ˈsaɪləns aɪz ˈɡəʊldən/", "I like to spend time in quiet places – silence is golden.", ""],
    ["sleeping tablet n", "/ˈsliːpɪŋ ˈtæblət/", "I took a sleeping tablet to help me sleep last night.", ""],
    ["stay-at-home dad n", "/steɪ æt həʊm dæd/", "I’m a stay-at-home dad and my wife goes out to work.", ""],
    ["the Tube n", "/ðə tjuːb/", "I hate travelling on the Tube.", ""],
    ["trivial adj", "/ˈtrɪviəl/", "My daughter talks about trivial things like clothes and make-up.", ""],
    ["valuable adj", "/ˈvæljuəbl/", "My time is valuable so I don’t like to waste it.", ""],
]
